services:
  app:
    build: .
    container_name: ms_finance_control_app
    ports:
      - "5000:5000"
    volumes:
      # Monta o diretório do projeto para dentro do contêiner
      - .:/app
    environment:
      # Variáveis para o Flask encontrar e rodar a aplicação em modo debug
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: ms_finance_control_db
    # O healthcheck verifica se o MySQL está pronto para aceitar conexões.
    # O serviço 'app' só iniciará após o 'db' estar saudável.
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: