services:
  app:
    build: .
    container_name: ms_finance_control_app
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=fc_user
      - DATABASE_PASSWORD=fc_password
      - DATABASE_NAME=fc
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ms_finance_control_db
    restart: always
    environment:
      MYSQL_DATABASE: fc
      MYSQL_USER: fc_user
      MYSQL_PASSWORD: fc_password
      MYSQL_ROOT_PASSWORD: changeme # Altere para uma senha forte em produção
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: